### ISSUE TITLE
Finish the `large-datasets` branch

### ISSUE THREAD

**Issue by mradke** [mradke/elm-filter-list#1]
## Todo
- [x] Render only a small portion of the datastructure elements to the dom, depending on the scroll position
- [ ] do not recalculate the vertical position of each row on every scroll event
- [ ] recalculate the height of the list-container on change (i. e. when filtering)
- [ ] do some performance tests

In the end the performance shall be comparable to https://github.com/bvaughn/react-virtualized
